{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "neo4j.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "neo4j.fullname" . }}
  namespace: neo4j
spec:
  selector:
    matchLabels:
      app: {{ template "neo4j.name" . }}
      release: {{ .Release.Name | quote }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}
